name = "SHGO"
uuid = "0ee0e29c-01bb-55d7-8e26-92326ec34c1a"
version = "0.2.0"
authors = ["Uwe Alex"]

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NonlinearOptimizationTestFunctions = "3180b13f-e8d1-40aa-806b-3e6ce7522c6b"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1.10"
Combinatorics = "1"
NonlinearOptimizationTestFunctions = "0.6"
Optimization = "4"
OptimizationOptimJL = "0.4"
StaticArrays = "1"